### ISSUE TITLE
Tinplate steel

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfinityCore#3]
I'd like a "Tinplate Steel" item, ideally using the attached texture.
![tinplate steel](https://cloud.githubusercontent.com/assets/2825989/14502204/06f9d3c0-015f-11e6-8374-f2b983ed901a.png)

Please comment with the item name if/when added.

**Comment by JasonMcRay** [comment]
It will be InfinityCore:itemMaterial:18

Do you also need oredict? Or not?

**Comment by Timeslice42** [comment]
Nah, I don't see any reason for that.
