### ISSUE TITLE
gregtech

### ISSUE THREAD

**Issue by SvEgiiVEteR** [JasonMcRay/InfinityCore#4]
my request may seem strange.
but you could do InfinityCore1.6 for gregtech-5.08.33.jar
33 version crash.
if not difficult...please

**Comment by JasonMcRay** [comment]
InfinityCore is made only for Infitech modpack. So no i am not going to make it for other purposes.

**Comment by SvEgiiVEteR** [comment]
Oh...sad..
thanks for the reply
